name: Deploy to AWS, docker CI/CD

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: hub.docker.com
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
  CONTAINER_NAME: ${{ secrets.DOCKER_BACKEND_IMAGE }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
        IMAGE_TAG: ${{ env.CONTAINER_NAME }}-${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $REPOSITORY:$IMAGE_TAG .
        docker push $REPOSITORY:$IMAGE_TAG
        echo "image=$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
